.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CERTIFIED" "1" "February 2014" "" "Certified"
.
.SH "NAME"
\fBcertified\fR \- generate and sign certificates
.
.SH "SYNOPSIS"
\fBcertified\fR [\fB\-\-bits\fR=\fIbits\fR] [\fB\-\-days\fR=\fIdays\fR] [\fB\-\-db\fR=\fIdb\fR] [\fB\-\-name\fR=\fIname\fR] [\fB\-\-no\-sign\fR] [\fB\-\-password\fR=\fIpassword\fR] [\fB\-\-revoke\fR] [\fB\-\-self\-signed\fR] [\fBC\fR=\fIcountry\fR] [\fBST\fR=\fIstate\fR] [\fBL\fR=\fIlocality\fR] [\fBO\fR=\fIorganization\fR] \fBCN\fR=\fIcommon\-name\fR [\fB+\fR\fIdns\fR[\fI\.\.\.\fR]] [\fB+\fR\fIip\fR[\fI\.\.\.\fR]]
.
.SH "DESCRIPTION"
Generate and sign a certificate with the CA in \fIdb\fR unless \fB\-\-revoke\fR is given, in which case the certificate is revoked instead\.
.
.P
Additional DNS names, including wildcards, and IP addresses can be added to the certificate using the \fB+\fR option\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-bits\fR=\fIbits\fR
Bits to use for the private key (defaults to \fI2048\fR)\.
.
.TP
\fB\-\-days\fR=\fIdays\fR
Days until the certificate expires (defaults to \fI3650\fR)\.
.
.TP
\fB\-\-db\fR=\fIdb\fR
OpenSSL database directory (defaults to \fIetc/ssl\fR)\.
.
.TP
\fB\-\-name\fR=\fIname\fR
Filename to use (default derived from the certificate common name)\.
.
.TP
\fB\-\-no\-sign\fR
Do not sign the certificate; stop with a certificate signing request\. Relay this certificate signing request to your certificate vendor\.
.
.TP
\fB\-\-password\fR=\fIpassword\fR
Password for the CA private key\.
.
.TP
\fB\-\-revoke\fR
Revoke an existing certificate\.
.
.TP
\fB\-\-self\-signed\fR
Generate a self\-signed certificate instead of using the CA\.
.
.TP
\fBC\fR=\fIcountry\fR
Certificate country (defaults to the CA country)\.
.
.TP
\fBST\fR=\fIstate\fR
Certificate state (defaults to the CA state)\.
.
.TP
\fBL\fR=\fIlocality\fR
Certificate Locality (usually a city; defaults to the CA locality)\.
.
.TP
\fBO\fR=\fIorganization\fR
Certificate organization (usually a company; defaults to the CA organization)\.
.
.TP
\fBCN\fR=\fIcommon\-name\fR
Certificate common name (usually a domain name)\.
.
.TP
\fB+\fR\fIdns\fR, \fB+\fR\fIip\fR
Add a DNS name or IP address to the certificate\'s subject alternative names\.
.
.SH "THEME SONG"
Led Zeppelin \- "Fool in the Rain"
.
.SH "AUTHOR"
Richard Crowley \fIr@rcrowley\.org\fR
.
.SH "SEE ALSO"
\fBcertified\-ca\fR(1), \fBcertified\-yaml\fR(1)
.
.P
\fBcertified\-csr\fR(1), \fBcertified\-crt\fR(1), \fBcertified\-revoke\fR(1)
.
.P
\fBopenssl\fR(1), \fBca\fR(1), \fBgenrsa\fR(1), \fBreq\fR(1), \fBx509\fR(1)
.
.P
\fIhttps://github\.com/rcrowley/certified/wiki\fR
