.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CERTIFIED\-YAML" "1" "February 2014" "" "Certified"
.
.SH "NAME"
\fBcertified\-yaml\fR \- generate Hiera\-compatible YAML
.
.SH "SYNOPSIS"
\fBcertified\-yaml\fR [\fB\-\-db\fR=\fIdb\fR]
.
.SH "DESCRIPTION"
Generate Hiera\-compatible YAML containing all certificates and all private keys except the CA private key\. The YAML is written to standard output\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-db\fR=\fIdb\fR
OpenSSL database directory (defaults to \fIetc/ssl\fR)\.
.
.SH "THEME SONG"
Led Zeppelin \- "Fool in the Rain"
.
.SH "AUTHOR"
Richard Crowley \fIr@rcrowley\.org\fR
.
.SH "SEE ALSO"
\fBcertified\fR(1), \fBcertified\-ca\fR(1)
.
.P
\fBcertified\-csr\fR(1), \fBcertified\-crt\fR(1), \fBcertified\-revoke\fR(1)
.
.P
\fIhttps://github\.com/rcrowley/certified/wiki\fR
